// GENERATED — do not edit. Run :kmp:generateDemoFileSystem to regenerate.
// Source: kmp/src/commonMain/resources/demo-graph/
package dev.stapler.stelekit.platform

import kotlin.time.Clock
import kotlinx.datetime.TimeZone
import kotlinx.datetime.todayIn

/**
 * An in-memory FileSystem implementation for the browser demo.
 * Provides pre-seeded content so the wasmJs demo loads with meaningful pages
 * without requiring a real filesystem or SQLite driver.
 *
 * This file is generated by the :kmp:generateDemoFileSystem Gradle task.
 * Do not edit manually — changes will be overwritten on the next build.
 */
class DemoFileSystem : FileSystem {
    private val today = Clock.System.todayIn(TimeZone.currentSystemDefault())
    private val journalFileName =
        "${today.year}_${today.monthNumber.toString().padStart(2, '0')}_${today.dayOfMonth.toString().padStart(2, '0')}.md"

    private val journalTemplate = """
- date:: {DATE}
- tags:: #journal #welcome
- Welcome to SteleKit! You are reading the demo graph — a live, editable example of what a SteleKit graph looks like.
  - Everything you see is stored as plain Markdown files, compatible with Logseq.
  - Edit any block right now. Your changes stay in the demo — nothing is permanent here.
- **Where to start**
  - Head to [[Start Here]] for a full index of feature pages.
  - Or dive straight into one of the highlights below.
- **Five things to try in the next five minutes**
  - Type `[[` in any block to create a wiki link — a suggestion dropdown appears instantly.
  - Press `Tab` to indent the current block and make it a child of the one above.
  - Press `Cmd+K` (macOS) or `Ctrl+K` (Windows/Linux) to open full-text search.
  - Add `card:: true` as a child of any block, then open the Flashcards screen to review it.
  - Type `TODO ` at the start of a block to mark it as a task — cycle through `TODO → DOING → DONE`.
- **What makes SteleKit different**
  - ==Every block is linkable.== You can link to a page, but you can also link to a single block inside any page.
  - Local-first — your notes live on disk as `.md` files. No account required, no lock-in.
  - The same graph files work in Logseq unchanged — you own your data.
- Explore the demo, break things, then open your own graph folder when you are ready to start for real.

    """.trimIndent()

    private val overrides = mutableMapOf<String, String>()

    private val demoFiles: Map<String, String> = buildMap {
        put("pages/About SteleKit.md", """
- tags:: #explanation #about
- SteleKit is a Kotlin Multiplatform reimplementation of the core concepts behind Logseq — a local-first, Markdown-based outliner and knowledge graph tool.
- **What SteleKit is**
	- A block-based outliner: every piece of content is a bullet block, nestable to any depth.
	- A knowledge graph: pages connect to each other via `[[wiki links]]`, forming a web of ideas.
	- A daily journal: a dedicated page for each calendar day captures your running log.
	- A Markdown-native app: all data is stored as plain `.md` files you can read with any editor.
- **Kotlin Multiplatform**
	- SteleKit is built with Kotlin Multiplatform (KMP) and Compose Multiplatform.
	- A single shared codebase targets Desktop (JVM), Android, and iOS.
	- The same UI, the same graph logic, and the same parser run on every platform.
	- Web is enabled as an optional build target.
- **Logseq compatibility**
	- SteleKit uses the same `pages/` + `journals/` directory layout as Logseq.
	- The Markdown format is compatible: a graph opened in SteleKit can be opened in Logseq and vice versa.
	- This means your notes are not locked in — you own the files, and any Markdown-aware tool can read them.
- **Local-first philosophy**
	- All data lives in files on your device. No server, no account, no sync service required.
	- You choose where to store your graph (local folder, iCloud, Dropbox, etc.).
	- SteleKit reads and writes your files directly.
- **Open source**
	- The project is open source. Contributions, bug reports, and feature requests are welcome.
- Return to [[Start Here]] to explore all feature pages in this demo graph.
""".trimIndent())
        put("pages/All Pages.md", """
- tags:: #reference
- The All Pages view lists every non-journal page in your graph.
- **What is shown**
	- All pages in the `pages/` directory of the graph, sorted alphabetically by title.
	- Journal entries (stored in `journals/`) are not listed here — use the Journals view for those.
	- Newly created pages appear in the list immediately after they are saved.
- **Navigating to a page**
	- Tap or click any page name in the list to open it.
	- The page opens in the main content area; the sidebar stays visible on desktop.
- **Tips**
	- Use All Pages to audit your graph — look for pages that have no links (orphans).
	- An alphabetical list is useful for quickly jumping to a known page name without searching.
	- Combine with [[Search]] for finding pages when you only remember a word from the content.
""".trimIndent())
        put("pages/Backlinks.md", """
- tags:: #reference #backlinks
- Backlinks are automatic reverse references. When page A links to page B, page B automatically knows about it.
- **The References Panel**
	- The sidebar shows a "Referenced in" section for the current page.
	- Each entry shows the page that contains a link to here, along with the block that contains the link.
	- You can read the context of the reference without navigating away.
- **Pages that link here**
	- [[Block Editing]] links to this page via the See Also mention at the bottom.
	- [[Page Linking]] links here to explain the receiving side of a wiki link.
	- Any journal entry that mentions `[[Backlinks]]` will also appear here.
- **Bidirectional linking model**
	- Linking is a two-way relationship. You write a link in one direction; the reverse appears automatically.
	- This means you never need a separate "Related pages" section — the graph computes it for you.
	- The result is a web of connected ideas rather than a hierarchy of folders.
- **Tips**
	- Use the References Panel to discover unexpected connections between notes.
	- A page with many backlinks is a hub — a high-value concept worth refining.
- See [[Page Linking]] to learn how to create links, and [[Block Editing]] for general editing.
""".trimIndent())
        put("pages/Block Editing.md", """
- tags:: #how-to #editing
- Blocks are the primary unit of content in SteleKit. Every line of text is a block.
	- Blocks can be nested to any depth, creating an outline hierarchy.
	- A page is simply a named list of blocks.
- **Creating blocks**
	- Click anywhere on the page to focus the editor.
	- Type your content and press **Enter** to create a new block below.
	- Press **Backspace** on an empty block to delete it and move focus up.
- **Indenting and nesting**
	- Press **Tab** to indent a block — it becomes a child of the block above it.
	- Press **Shift+Tab** to unindent — the block moves up one level in the hierarchy.
	- Children collapse under their parent when you click the bullet triangle.
- **Example: a nested block structure**
	- Project Alpha
		- Research phase
			- Read background papers
			- Interview stakeholders
		- Implementation phase
			- Write first draft
			- Review with team
	- Project Beta
		- Planning
		- Execution
- **Tips**
	- Use deep nesting to capture sub-tasks, sub-ideas, or supporting evidence.
	- Keep top-level blocks as main ideas; nest the details beneath them.
	- A flat structure with many blocks works just as well — choose what feels natural.
- See [[Block Editor Reference]] for the full list of keyboard shortcuts and block states.
""".trimIndent())
        put("pages/Block Editor Reference.md", """
- tags:: #reference #keyboard-shortcuts
- This page is a quick reference for block editing interactions. See [[Block Editing]] for step-by-step guidance.
- **Keyboard Shortcuts**
	- Block creation and deletion
		- `Enter` — create a new block below the current block
		- `Backspace` on an empty block — delete the block, move cursor to block above
		- `Shift+Enter` — insert a line break within the current block (soft newline)
	- Indentation
		- `Tab` — indent the current block (makes it a child of the block above)
		- `Shift+Tab` — unindent the current block (promotes it to the parent's level)
	- Navigation
		- `Arrow Up` / `Arrow Down` — move cursor between blocks
		- `Ctrl+Home` — jump to the first block on the page
		- `Ctrl+End` — jump to the last block on the page
- **Block States**
	- Focused — the block the cursor is in; shows an edit cursor
	- Editing — actively receiving keyboard input
	- Read-only — blocks rendered outside the editor (e.g. in the sidebar references panel)
	- Collapsed — a parent block whose children are hidden; click the triangle bullet to expand
- **Block Selection**
	- Click a bullet point to select a block for drag-and-drop reordering.
	- Selected blocks highlight with a subtle background color.
- **Inline Formatting Shortcuts**
	- `**text**` — bold
	- `*text*` — italic
	- `` `text` `` — inline code
	- `~~text~~` — strikethrough
- See [[Markdown Formatting]] for the complete inline markup reference.
""".trimIndent())
        put("pages/Daily Notes.md", """
- tags:: #how-to #journal
- Daily Notes (also called Journals) give you a dedicated page for each calendar day.
	- Think of it as a captain's log — a running record of thoughts, tasks, and events.
	- Each day's entry is a separate Markdown file in the `journals/` directory.
- **Opening the Journals view**
	- Tap or click the Journals icon in the sidebar.
	- The view shows entries in reverse-chronological order (newest at the top).
	- Scroll down to see older entries.
- **Navigating to today's note**
	- The top of the Journals view always shows today's entry.
	- If no entry exists for today, the view shows an empty block ready to receive your first note.
	- Start typing to create your first block for the day.
- **Navigating to past dates**
	- Scroll down in the Journals view to reach earlier dates.
	- Each date header is a link — tap it to open that date as a full page.
	- You can also create a wiki link like `[[2026-04-12]]` from any page to jump directly to that entry.
- **Example journal entry** — see [[2026-04-12]] for a sample weekly-review entry.
- **Tips**
	- Use the daily note as an inbox: capture ideas quickly, then move them to dedicated pages later.
	- Link from your daily note to reference pages using `[[Page Name]]` to create a trail of context.
""".trimIndent())
        put("pages/Flashcards.md", """
- tags:: #how-to #flashcards
- SteleKit's flashcard feature turns any block into a spaced-repetition review card.
	- Spaced repetition is a learning technique that schedules reviews at increasing intervals.
	- Cards you know well are shown less often; cards you struggle with appear more frequently.
- **Marking a block as a flashcard**
	- Add the block property `card:: true` as an indented child of any block.
	- Example:
		- The mitochondria is the powerhouse of the cell.
			- card:: true
	- Any block with `card:: true` enters the review queue.
- **Opening the review queue**
	- Tap the Flashcards icon in the sidebar (or navigate via Screen > Flashcards).
	- Cards due for review are shown one at a time.
	- Read the front of the card, recall your answer, then reveal the back.
- **Rating your recall**
	- After revealing the answer, rate how well you remembered it.
	- The scheduler adjusts the next review date based on your rating.
	- Cards rated "Again" return to the queue soon; cards rated "Easy" are deferred longer.
- **Tips**
	- Keep flashcard blocks short — one fact per card works best for recall.
	- Use block nesting: put the question as the parent block and the answer as a child with `card:: true`.
	- Review your queue daily for best results.
- See [[Properties]] for more about the `key:: value` block property syntax.
""".trimIndent())
        put("pages/Images.md", """
- tags:: #how-to #images
- SteleKit renders images embedded in blocks using standard Markdown image syntax.
- **Syntax**
	- `![alt text](path/to/image.png)`
	- The alt text is shown if the image cannot load; it also aids accessibility.
	- The path is relative to the page file or an absolute URL.
- **Embedded image example**
	- The block below embeds an image from the `assets/` directory bundled with this demo graph:
	- ![SteleKit block hierarchy diagram](../assets/stelekit-diagram.png)
- **Image paths**
	- For images in the same graph, use a relative path from the page to the asset:
		- Pages are in `pages/` → use `../assets/filename.png`
		- Journal entries are in `journals/` → use `../assets/filename.png`
	- For external images, use a full URL: `![alt](https://example.com/image.png)`
- **Assets directory**
	- Store image files in the `assets/` folder inside your graph directory.
	- Images in `assets/` are bundled with the demo graph and available on all platforms.
	- Supported formats: PNG, JPEG, GIF, WebP, and SVG.
- **Tips**
	- Always write descriptive alt text — it describes the image for screen readers and search.
	- Keep image files small (under 1 MB ideally) for fast loading on mobile.
	- Use PNG for diagrams and screenshots; JPEG for photographs.
- See [[Markdown Formatting]] for other inline markup supported in SteleKit.
""".trimIndent())
        put("pages/Keyboard Shortcuts.md", """
- tags:: #reference #keyboard-shortcuts
- All keyboard shortcuts available in SteleKit, organized by category.
- **Navigation**
	- `Cmd+K` / `Ctrl+K` — open the search dialog
	- `Arrow Up` / `Arrow Down` — move between blocks
	- `Ctrl+Home` — jump to the first block on the page
	- `Ctrl+End` — jump to the last block on the page
	- Click a wiki link — navigate to the linked page
	- Browser Back / `Alt+Left` — return to the previous page
- **Block editing**
	- `Enter` — create a new block below the current block
	- `Backspace` on an empty block — delete the block
	- `Shift+Enter` — insert a soft line break within the current block
	- `Tab` — indent (make child of the block above)
	- `Shift+Tab` — unindent (promote to parent's level)
- **Inline formatting**
	- `**text**` — bold
	- `*text*` — italic
	- `~~text~~` — strikethrough
	- `` `text` `` — inline code
	- `[[` — begin a wiki link (shows suggestion dropdown)
- **Sidebar**
	- Click the sidebar toggle button — show or hide the left sidebar
	- On desktop, the sidebar opens automatically at startup
	- On mobile, the sidebar is hidden by default; tap the menu icon to open it
- **Search dialog**
	- `Escape` — close the search dialog
	- `Arrow Up` / `Arrow Down` — move through search results
	- `Enter` — open the selected result
- **Flashcards**
	- Navigate to the Flashcards screen via the sidebar icon
	- Space or `Enter` — reveal the answer for the current card
	- Number keys `1`–`4` — rate your recall (Again / Hard / Good / Easy)
- **Tips**
	- On macOS, use `Cmd` where Windows/Linux uses `Ctrl`.
	- Most shortcuts work the same across Desktop, Android (hardware keyboard), and Web.
- See [[Block Editor Reference]] for block-specific shortcuts, and [[Search]] for search tips.
""".trimIndent())
        put("pages/Markdown Formatting.md", """
- tags:: #reference #formatting
- SteleKit renders standard inline Markdown within every block.
- **Text emphasis**
	- Bold: `**bold text**` → **bold text**
	- Italic: `*italic text*` → *italic text*
	- Bold and italic combined: `***bold italic***` → ***bold italic***
	- Strikethrough: `~~struck through~~` → ~~struck through~~
	- Highlight: `==important text==` → ==important text==
- **Inline code**
	- Wrap text in backticks: `` `code here` `` → `code here`
	- Use inline code for file paths, variable names, and commands.
- **Headings (in outliner mode)**
	- Add `# ` at the start of a block to render it as a heading.
	- `# Heading 1`, `## Heading 2`, `### Heading 3` are all supported.
	- Note: in an outliner, headings are rarely needed — use nesting for hierarchy instead.
- **Blockquotes**
	- Prefix a block with `> ` to render it as a blockquote.
	- Example: `> This is a quoted passage.` → renders with a left-border indent.
	- Use for quotes, callouts, or content lifted from another source.
- **Fenced code blocks**
	- Use triple backticks with an optional language identifier.
	- Example — a Kotlin snippet:
		- ```kotlin
val greeting = "Hello, SteleKit"
println(greeting)
```
- **Links**
	- External links: `[link text](https://example.com)`
	- Wiki links: `[[Page Linking]]` is an example — see [[Page Linking]] for full details
- **Tags**
	- Add `#tag-name` inline in any block to tag it.
	- Tags are searchable and appear in the [[Tags & Highlight]] reference page.
- **Support status**
	- Fully supported: bold, italic, strikethrough, inline code, highlight, fenced code blocks, blockquotes, wiki links, external links, tags, tables
	- Partially supported: headings (rendered but outliner hierarchy is preferred)
- See [[Block Editor Reference]] for editing shortcuts, [[Tables]] for pipe-table syntax, and [[Tags & Highlight]] for tag and highlight details.
""".trimIndent())
        put("pages/Page Linking.md", """
- tags:: #how-to #linking
- Wiki links connect pages together and form the knowledge graph at the heart of SteleKit.
- **Syntax**
	- Wrap any page name in double square brackets: `[[Page Name]]`
	- The link becomes clickable and navigates to that page.
	- If the target page does not exist yet, clicking the link creates it.
- **Creating a link**
	- Type `[[` anywhere in a block.
	- A suggestion dropdown appears with matching page names.
	- Select a suggestion with arrow keys and Enter, or keep typing to narrow the list.
	- Press `]]` or Enter to confirm the link.
- **Automatic backlinks**
	- Every time you link to a page, SteleKit records that link automatically.
	- The linked page gains a "Referenced in" entry in its sidebar.
	- This means backlinks require zero extra effort — they are a side effect of linking.
	- See [[Backlinks]] for how to read the References Panel.
- **Example links in this graph**
	- [[Start Here]] — the index page and navigation hub
	- [[Block Editing]] — how to work with blocks
	- [[Properties]] — structured metadata with `key:: value` syntax
	- [[Keyboard Shortcuts]] — all shortcuts in one place
- **Tips**
	- Link generously. The graph becomes more useful as pages connect.
	- Use links instead of copy-pasting content — link to the source page.
	- You can link to a page from a journal entry to connect daily notes to reference material.
- See [[Backlinks]] to understand what happens on the receiving end of a link.
""".trimIndent())
        put("pages/Properties.md", """
- type:: how-to
- tags:: #how-to #reference #properties
- Properties attach structured `key:: value` metadata to pages and blocks.
	- They are plain text in the Markdown file — no special syntax or frontmatter.
	- Any tool that reads Markdown can see them.
- **Page-level properties**
	- A page property is written as the first block (or first few blocks) of the page.
	- Format: `key:: value` on its own line, as a top-level bullet.
	- Example — this very page has `type:: how-to` at the top.
	- Common page properties:
		- `type:: how-to` or `type:: reference` — document type
		- `status:: draft` or `status:: published` — workflow state
		- `author:: Your Name` — attribution
		- `date:: 2026-04-13` — creation or modification date
- **Block-level properties**
	- A block property is a child bullet directly below the block it annotates.
	- Format: indented line with `key:: value` syntax.
	- The property belongs to the parent block above it, not to the page.
- **Example: a book note with block properties**
	- Atomic Habits by James Clear
		- author:: James Clear
		- rating:: 5
		- status:: finished
		- genre:: self-improvement
	- The Power of Habit by Charles Duhigg
		- author:: Charles Duhigg
		- rating:: 4
		- status:: reading
- **Tips**
	- Property keys are case-sensitive: `Author::` and `author::` are different keys.
	- Values are always treated as strings unless a plugin or query interprets them otherwise.
	- Use consistent key names across pages to enable graph-wide queries in the future.
- See [[Block Editing]] for how to work with blocks, and [[Start Here]] for navigation.
""".trimIndent())
        put("pages/Search.md", """
- tags:: #how-to #search
- SteleKit's search dialog lets you find any page or block across your entire graph instantly.
- **Opening search**
	- Press `Cmd+K` on macOS or `Ctrl+K` on Windows and Linux.
	- The search dialog opens with a text field and a list of recent pages.
	- Start typing immediately — results update with each keystroke.
- **How search works**
	- Search scans page titles and block content across all loaded graphs.
	- Results are ranked by relevance: exact matches rank above partial matches.
	- Page title matches rank above block-content matches.
- **Finding pages vs. blocks**
	- Results show the page title and, for block matches, a snippet of the matching block.
	- Click any result to navigate directly to that page or block.
	- If the match is a block deep in a long page, the page opens with the matched block highlighted.
- **Tips**
	- Search for a page name to jump to it without using the sidebar.
	- Use search to discover pages you forgot you created.
	- Searching for a tag like `#reference` surfaces all pages with that tag in their content.
- See [[All Pages]] for browsing pages alphabetically without a search query.
""".trimIndent())
        put("pages/Start Here.md", """
- type:: index
- tags:: #welcome #getting-started
- Welcome to SteleKit — your Logseq-compatible outliner for Desktop, Android, and iOS.
	- This graph is both a working demo and a built-in help reference.
	- Every feature has a dedicated page. Read it, edit it, link from it.
- This graph is portable. The same `.md` files open in Logseq unchanged.
- **Feature Pages** — explore SteleKit's capabilities:
	- [[Block Editing]] — create, indent, and reorder blocks; the primary unit of content
	- [[Block Editor Reference]] — keyboard shortcuts and block states at a glance
	- [[Page Linking]] — connect pages with `[[double bracket]]` wiki links
	- [[Backlinks]] — the References Panel and bidirectional linking model
	- [[Properties]] — add structured `key:: value` metadata to pages and blocks
	- [[Tags & Highlight]] — `#tag-name` inline tags and `==highlighted text==`
	- [[Daily Notes]] — the Journals view and navigating between dates
	- [[Search]] — full-text search with Cmd+K / Ctrl+K
	- [[All Pages]] — browse every non-journal page alphabetically
	- [[Flashcards]] — mark blocks for spaced-repetition review
	- [[Markdown Formatting]] — bold, italic, highlight, blockquotes, code, headings, and more
	- [[Tables]] — GFM pipe-table syntax
	- [[Tasks]] — TODO/DOING/DONE markers and scheduled/deadline timestamps
	- [[Images]] — embed images with `![alt](path)` syntax
	- [[Keyboard Shortcuts]] — full shortcut reference organized by category
	- [[About SteleKit]] — what SteleKit is and how it relates to Logseq
- **Getting Started**
	- Open [[Block Editing]] to learn the fundamentals.
	- Then visit [[Page Linking]] to see how the graph grows as you connect ideas.
	- Check [[Daily Notes]] to start a daily journaling habit.
	- Try [[Tags & Highlight]] to quickly categorize and emphasize content.
- This page is your home base. Bookmark it or link to it from your own pages.
""".trimIndent())
        put("pages/Tables.md", """
- tags:: #reference #tables
- SteleKit renders GFM pipe tables natively inside blocks.
- **Syntax**
	- A table has a header row, a separator row, and data rows.
	- Each column is separated by a pipe character `|`.
	- The separator row uses hyphens `---` in each column cell.
	- Column alignment: `:---` = left, `:---:` = center, `---:` = right.
- **Example — feature support table**

| Feature         | Status    | Notes                             |
|:----------------|:---------:|----------------------------------:|
| Bold / italic   | Supported | Use `**` and `*` markers          |
| Inline code     | Supported | Use backticks                     |
| Highlight       | Supported | Use `==text==`                    |
| Wiki links      | Supported | Use `[[double bracket]]` syntax   |
| Tables          | Supported | GFM pipe-table syntax (this page) |
| Tags            | Supported | Use `#tag-name` inline            |
| Task markers    | Supported | TODO, DOING, DONE prefix syntax   |

- **Tips**
	- Tables render inside any block — paste the markdown directly.
	- Use alignment markers to control column layout: `:---` left, `:---:` center, `---:` right.
	- For simple comparisons, nested blocks can also work well as an alternative.
- See [[Markdown Formatting]] for all supported inline markup, and [[Properties]] for `key:: value` metadata syntax.
""".trimIndent())
        put("pages/Tags & Highlight.md", """
- tags:: #reference #tags #highlight
- SteleKit supports inline `#tags` for categorizing content and `==highlight==` for visual emphasis.
- **Tags**
	- Type `#` followed by a word anywhere in a block to tag it: `#idea`, `#reference`, `#todo`
	- Multi-word tags use hyphens: `#project-alpha`, `#follow-up`
	- Tags are searchable — use `Cmd+K` / `Ctrl+K` and type the tag name to find all tagged blocks.
	- Tags appear in the block as styled inline text so they stand out visually.
	- Example blocks using tags:
		- Read this paper before the meeting #important #reading
		- Idea: use tags as a lightweight status system #idea
		- This reference lives here permanently #reference #evergreen
- **Highlight**
	- Wrap text in `==double equals==` to highlight it: `==key insight==` → ==key insight==
	- Use highlight to mark the most important sentence in a block.
	- Combine with bold for maximum emphasis: `**==critical==**` → **==critical==**
	- Example:
		- The most important rule: ==every block is linkable, searchable, and reviewable==.
		- Highlights are rendered inline — ==they do not disrupt the outline flow==.
- **Combining tags and highlight**
	- Tags categorize a block; highlight emphasizes a phrase within the block text.
	- They complement each other: tag the block's topic, highlight the key takeaway.
	- Example:
		- ==Spaced repetition== dramatically improves long-term recall — even brief daily review compounds over time. #learning #flashcards
- **Tips**
	- Keep tag names short and consistent — use the same tag across pages to group related content.
	- Use search (Cmd+K / Ctrl+K) and type `#tag-name` to surface all blocks with that tag.
	- Prefer highlight over bold when you want to mark something as important without implying strong text emphasis.
- See [[Search]] to find tagged blocks, [[Markdown Formatting]] for all inline syntax, and [[Flashcards]] to turn highlighted blocks into spaced-repetition cards.
""".trimIndent())
        put("pages/Tasks.md", """
- tags:: #reference #tasks
- SteleKit supports Logseq-style task markers as a prefix on any block.
- **Logseq-style task markers**
	- Add a marker keyword at the start of a block to set its state.
	- Supported markers: `TODO`, `DOING`, `DONE`, `NOW`, `LATER`, `WAITING`, `WAIT`, `STARTED`, `CANCELLED`
	- Examples:
		- TODO Write the introduction section
		- DOING Review pull request comments
		- DONE Set up the project repository
		- LATER Follow up with the design team
		- WAITING Awaiting feedback from the design team
		- CANCELLED Migrate old notes from Evernote
- **Cycling task state**
	- Use the block menu or keyboard shortcut to cycle a block through: `TODO → DOING → DONE → TODO`
	- Markers are stored as plain text in the Markdown file — Logseq-compatible.
- **SCHEDULED and DEADLINE timestamps**
	- Add a timestamp property to a block to schedule it or record a hard deadline.
	- Use `key:: value` child block syntax (see [[Properties]]).
	- Example:
		- Prepare release notes
			- scheduled:: 2026-04-14
			- deadline:: 2026-04-15
- **Tips**
	- Task markers are plain text — you can type them directly or toggle them from the block menu.
	- Pair tasks with [[Properties]] to add context: `priority:: high`, `project:: SteleKit`.
	- Logseq-compatible: these task markers open correctly in Logseq with no conversion needed.
- See [[Properties]] for `key:: value` syntax, and [[Markdown Formatting]] for other inline markup.
""".trimIndent())
        put("pages/Unlinked References.md", """
- Unlinked References shows every mention of a page name that is not yet a `[[wikilink]]`.
- Open it from the sidebar to see suggested links across your entire graph.
  - Each entry shows the block text and which page it could link to.
  - Tap **Link** to convert the mention to a `[[wikilink]]` automatically.
  - Tap **Ignore** to dismiss the suggestion without linking.
- Linking unlinked references improves your graph's connectivity.
  - More wikilinks means more backlinks, which makes the graph view richer.
  - Use this view periodically to catch pages you reference by name but never formally linked.
""".trimIndent())
        put("journals/2026_04_08.md", """
- date:: 2026-04-08
- tags:: #journal #first-day
- First time opening SteleKit today. The interface is clean — just a sidebar, a content area, and an empty block waiting for input.
	- The block-based editing model is immediately different from every other note-taking app I have used.
	- In Word or Notion, I write paragraphs. Here, every sentence can become its own node in a tree.
- Spent an hour reading [[Block Editing]]. A few things clicked:
	- Blocks are not just visual. They are the unit of linking, querying, and reviewing.
	- Nesting with Tab feels more natural than I expected.
	- You can collapse subtrees — this changes how I think about large topics.
- **First impressions**
	- The outliner is faster to navigate than a prose document once you get used to it.
	- Backlinks are automatic — I did not have to do anything to get them.
	- The `[[` shortcut for wiki links is clever; the suggestion dropdown appeared immediately.
	- Journal entries as daily pages is a much better habit-loop than a dedicated "daily notes" app.
- One confusion: I expected Enter to create a paragraph break. It creates a new block. That is the right behavior once you understand the model, but it is a shift.
- Plan for tomorrow: explore page linking and see how the graph builds up.
""".trimIndent())
        put("journals/2026_04_09.md", """
- date:: 2026-04-09
- tags:: #journal #linking
- Spent time today experimenting with `[[wiki links]]` between pages.
	- Created a new page called "Reading List" and linked it from today's journal entry.
	- The link appeared immediately in the suggestions dropdown after I typed `[[R`.
	- Clicking the link navigated to the new page in one tap.
- Discovered the backlinks panel while on the Reading List page.
	- The sidebar showed "Referenced in: 2026-04-09" with the exact block that linked here.
	- This is the killer feature — I never have to manually maintain a "pages that reference this" list.
	- Read [[Page Linking]] to understand the full mechanics, then [[Backlinks]] for the receiving side.
- A question I had: *How do I see all pages that link here?*
	- Answer: look at the References Panel in the sidebar. Every inbound link appears there automatically.
	- The panel shows the linking page name and a preview of the block containing the link.
- **Observations on the linking model**
	- Creating a link is a side effect of writing. It does not feel like extra work.
	- The graph grows naturally as I connect ideas rather than filing them into folders.
	- A page with many backlinks becomes a hub — worth revisiting and refining.
- Tomorrow: try adding properties to a page to see how structured metadata works.
""".trimIndent())
        put("journals/2026_04_10.md", """
- date:: 2026-04-10
- tags:: #journal #properties
- Properties experiment today — read [[Properties]] end to end and then tried it on a research page.
- Created a page called "Research: Spaced Repetition" and added page-level properties at the top:
	- author:: Various
	- status:: in-progress
	- topic:: learning science
	- started:: 2026-04-10
- Then added block-level properties to individual note blocks:
	- A block summarising a paper got `source:: Ebbinghaus 1885` and `confidence:: high` as child properties.
	- A block with an open question got `status:: unresolved`.
- **What properties enable**
	- Properties turn a freeform note into a structured record.
	- You can scan a page and immediately know its status, author, and topic without reading the full content.
	- In the future, graph-wide queries can filter pages by property values.
- Key insight: properties in SteleKit are just text with a `key:: value` pattern. There is no schema to configure. You invent your own vocabulary and stay consistent.
	- This is more flexible than a database but less rigorous. The trade-off feels right for personal notes.
- One thing to keep in mind: `Author::` and `author::` are different keys. Settle on lowercase conventions early.
- Tomorrow: first flashcard session. I want to see how the spaced-repetition queue works.
""".trimIndent())
        put("journals/2026_04_11.md", """
- date:: 2026-04-11
- tags:: #journal #flashcards
- First flashcard session today. Read [[Flashcards]] to understand how to set it up, then created a small deck from my spaced-repetition research notes.
- **Creating the first flashcard**
	- Opened the "Research: Spaced Repetition" page.
	- Found a block: "The forgetting curve shows retention drops sharply within 24 hours without review."
	- Added a child block: `card:: true`
	- The block immediately entered the review queue — no separate import step needed.
- **Reviewing the queue**
	- Opened the Flashcards screen from the sidebar.
	- The card appeared with the block text as the prompt.
	- Pressed Space to reveal — in this case the full block is both prompt and answer, so I was testing recall of the key fact.
	- Rated myself "Good" and the next review was scheduled automatically.
- **Notes on spaced repetition**
	- The value is not in the first review — it is in the second, third, and tenth review at the right intervals.
	- Short, atomic cards work better than long blocks. One fact per card.
	- The best time to create a flashcard is immediately after learning something, while the context is fresh.
- Converted five more blocks to flashcards across different pages. The queue already feels like a useful habit loop.
- Idea for tomorrow: weekly review of the week's notes and a summary of what I learned.
""".trimIndent())
        put("journals/2026_04_12.md", """
- date:: 2026-04-12
- tags:: #journal #review
- Weekly review. Five days with SteleKit — time to consolidate what I learned.
- **What I learned this week**
	- Block model
		- [[Block Editing]] — blocks are the atomic unit; Tab/Shift+Tab handle indentation naturally
		- Nesting is more expressive than I expected; collapse/expand changes how I read long pages
	- Linking and graph
		- [[Page Linking]] — `[[` shortcut and suggestion dropdown make linking effortless
		- Backlinks appear without any extra work; the graph grows as a side effect of writing
	- Structured data
		- [[Properties]] — `key:: value` syntax on page and block level; no schema needed
		- Consistent key naming is important from the start (lowercase convention)
	- Spaced repetition
		- [[Flashcards]] — `card:: true` property on any block adds it to the review queue
		- Atomic, short cards recall better than long blocks
- **What worked well**
	- Daily journal as inbox — capture first, file later. No friction at capture time.
	- Links instead of folders — the graph structure emerged naturally without planning a hierarchy.
	- The demo graph pages (this graph!) are useful reference material while learning.
- **Plans for next week**
	- Go deeper on [[Search]] — learn how to surface blocks by content, not just page titles.
	- Explore [[Markdown Formatting]] — want to use fenced code blocks for technical notes.
	- Set up a consistent property vocabulary for my research pages.
	- Keep the flashcard habit going: review queue every morning.
- One week in, SteleKit is already replacing two other apps for me. The local-first, Markdown-native approach feels right.
""".trimIndent())
        put("journals/2026_06_19.md", """
- date:: 2026-06-19
- tags:: #journal #welcome
- Welcome to SteleKit! You are reading the demo graph — a live, editable example of what a SteleKit graph looks like.
	- Everything you see is stored as plain Markdown files, compatible with Logseq.
	- Edit any block right now. Your changes stay in the demo — nothing is permanent here.
- **Where to start**
	- Head to [[Start Here]] for a full index of feature pages.
	- Or dive straight into one of the highlights below.
- **Five things to try in the next five minutes**
	- Type `[[` in any block to create a wiki link — a suggestion dropdown appears instantly.
	- Press `Tab` to indent the current block and make it a child of the one above.
	- Press `Cmd+K` (macOS) or `Ctrl+K` (Windows/Linux) to open full-text search.
	- Add `card:: true` as a child of any block, then open the Flashcards screen to review it.
	- Type `TODO ` at the start of a block to mark it as a task — cycle through `TODO → DOING → DONE`.
- **What makes SteleKit different**
	- ==Every block is linkable.== You can link to a page, but you can also link to a single block inside any page.
	- Local-first — your notes live on disk as `.md` files. No account required, no lock-in.
	- The same graph files work in Logseq unchanged — you own your data.
- Explore the demo, break things, then open your own graph folder when you are ready to start for real.
""".trimIndent())
        // Override with today's journal entry (date-substituted at runtime)
        put(
            "journals/${journalFileName}",
            journalTemplate
                .replace("{DATE}", "${today.year}-${today.monthNumber.toString().padStart(2, '0')}-${today.dayOfMonth.toString().padStart(2, '0')}")
                .replace("{YEAR}", today.year.toString())
                .replace("{MONTH}", today.monthNumber.toString().padStart(2, '0'))
                .replace("{DAY}", today.dayOfMonth.toString().padStart(2, '0'))
        )
    }

    override fun getDefaultGraphPath(): String = "/demo"
    override fun expandTilde(path: String): String = path

    override fun readFile(path: String): String? {
        return overrides[path] ?: demoFiles[path.removePrefix("/demo/")]
    }

    // Demo mode: writes are persisted in-memory for the session duration.
    // Content does not survive a page reload, but reads within the same session
    // reflect edits made via writeFile.
    override fun writeFile(path: String, content: String): Boolean {
        overrides[path] = content
        return true
    }

    override fun listFiles(path: String): List<String> {
        // Return file NAMES only (not full paths) — callers reconstruct "$path/$name" themselves.
        val prefix = path.removePrefix("/demo/").let { if (it.isEmpty()) "" else "$it/" }
        return (demoFiles.keys + overrides.keys.map { it.removePrefix("/demo/") })
            .filter {
                if (prefix.isEmpty()) {
                    // root: return only direct children (no nested paths)
                    !it.contains('/')
                } else {
                    it.startsWith(prefix)
                }
            }
            .map { it.removePrefix(prefix) }
            .distinct()
    }

    override fun listDirectories(path: String): List<String> {
        // Return directory NAMES only — callers construct full paths themselves.
        return if (path == "/demo" || path == "/demo/") {
            listOf("journals", "pages")
        } else emptyList()
    }

    override fun fileExists(path: String): Boolean {
        return overrides.containsKey(path) || demoFiles.containsKey(path.removePrefix("/demo/"))
    }

    // Only return true for directories that actually exist in the demo filesystem.
    // The previous implementation (`path.startsWith("/demo")`) caused detectGitRoot()
    // to find a false `/demo/.git` directory and show the git detection banner incorrectly.
    private val knownDirectories = setOf("/demo", "/demo/journals", "/demo/pages")
    override fun directoryExists(path: String): Boolean = path.trimEnd('/') in knownDirectories

    override fun createDirectory(path: String): Boolean = true
    override fun deleteFile(path: String): Boolean = true
    override fun pickDirectory(): String? = null
    override suspend fun pickDirectoryAsync(): String? = null
    override fun getLastModifiedTime(path: String): Long? = null
}
